// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package notification

import (
	"flai/api/notification"
)

type ControllerV1 struct{}

func NewV1() notification.INotificationV1 {
	return &ControllerV1{}
}
