// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package conversation

import (
	"flai/api/conversation"
)

type ControllerV1 struct{}

func NewV1() conversation.IConversationV1 {
	return &ControllerV1{}
}
