// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package translate

import (
	"flai/api/translate"
)

type ControllerV1 struct{}

func NewV1() translate.ITranslateV1 {
	return &ControllerV1{}
}
