// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"flai/internal/dao/internal"

	"github.com/gogf/gf/v2/os/gtime"
)

// conversationDao is the data access object for the table conversation.
// You can define custom methods on it to extend its functionality as needed.
type conversationDao struct {
	*internal.ConversationDao
}

var (
	// Conversation is a globally accessible object for table conversation operations.
	Conversation = conversationDao{internal.NewConversationDao()}
)

// Add your custom methods and functionality below.
type ConversationSearch struct {
	Highlight      string      `json:"highlight"`
	ConversationId string      `json:"conversation_id"`
	Title          string      `json:"title"`
	Icon           string      `json:"icon"`
	CreatedAt      *gtime.Time `json:"created_at"`
}
