// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"flai/internal/dao/internal"
)

// mcpDao is the data access object for the table mcp.
// You can define custom methods on it to extend its functionality as needed.
type mcpDao struct {
	*internal.McpDao
}

var (
	// Mcp is a globally accessible object for table mcp operations.
	Mcp = mcpDao{internal.NewMcpDao()}
)

// Add your custom methods and functionality below.
