// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"flai/internal/dao/internal"
	"flai/internal/model/do"
	"flai/internal/model/entity"
)

// messageDao is the data access object for the table message.
// You can define custom methods on it to extend its functionality as needed.
type messageDao struct {
	*internal.MessageDao
}

var (
	// Message is a globally accessible object for table message operations.
	Message = messageDao{internal.NewMessageDao()}
)

func FetchMessageHistory(ctx context.Context, messagePath []string) ([]*entity.Message, error) {
	if len(messagePath) == 0 {
		return nil, nil
	}

	var historyMessages []*entity.Message
	err := Message.Ctx(ctx).Where(do.Message{
		Id: messagePath,
	}).Scan(&historyMessages)
	if err != nil {
		return nil, err
	}

	// Build a map for quick lookup
	messageMap := make(map[string]*entity.Message, len(historyMessages))
	for _, msg := range historyMessages {
		messageMap[msg.Id] = msg
	}

	// Reorder messages to match the input messagePath order
	orderedMessages := make([]*entity.Message, 0, len(messagePath))
	for _, id := range messagePath {
		if msg, exists := messageMap[id]; exists {
			orderedMessages = append(orderedMessages, msg)
		}
	}

	return orderedMessages, nil
}
