// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"flai/internal/dao/internal"
	"flai/internal/model/do"
	"flai/internal/model/entity"
)

// messageDao is the data access object for the table message.
// You can define custom methods on it to extend its functionality as needed.
type messageDao struct {
	*internal.MessageDao
}

var (
	// Message is a globally accessible object for table message operations.
	Message = messageDao{internal.NewMessageDao()}
)

func FetchMessageHistory(ctx context.Context, messagePath []string) ([]*entity.Message, error) {
	var historyMessages []*entity.Message
	if len(messagePath) > 0 {
		err := Message.Ctx(ctx).Where(do.Message{
			Id: messagePath,
		}).Scan(&historyMessages)
		if err != nil {
			return nil, err
		}
		return historyMessages, nil
	}
	return nil, nil
}
