// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"flai/internal/dao/internal"
)

// providerDao is the data access object for the table admin.
// You can define custom methods on it to extend its functionality as needed.
type providerDao struct {
	*internal.ProviderDao
}

var (
	// Provider is a globally accessible object for table admin operations.
	Provider = providerDao{internal.NewProviderDao()}
)

// Add your custom methods and functionality below.
