// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"flai/internal/dao/internal"
)

// shareDao is the data access object for the table share.
// You can define custom methods on it to extend its functionality as needed.
type shareDao struct {
	*internal.ShareDao
}

var (
	// Share is a globally accessible object for table share operations.
	Share = shareDao{internal.NewShareDao()}
)

// Add your custom methods and functionality below.
