// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package mcp

import (
	"flai/api/mcp"
)

type ControllerV1 struct{}

func NewV1() mcp.IMcpV1 {
	return &ControllerV1{}
}
