// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package share

import (
	"flai/api/share"
)

type ControllerV1 struct{}

func NewV1() share.IShareV1 {
	return &ControllerV1{}
}
